export {default as Home } from "./Home"
export {default as History } from "./History"
export {default as CryptoDetail } from "./CryptoDetail"
export {default as News } from "./News"
export {default as Cryptocurrencies } from "./Cryptocurrencies"
export {default as Navbar } from "./Navbar"